sudo: false
language: node_js

node_js:
  - "8"

before_install:
  - cd functions
  - npm install -g mocha eslint

script:
  - npm test

notifications:
  webhooks:
    on_success: change
    on_failure: always
